import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { BackgroundGradientAnimation } from "@/components/ui/background-gradient-animation";
import BottomBar from "@/components/fixed-components/BottomBar";
import TopBar from "@/components/fixed-components/TopBar";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        
      >
        <div className="overflow-y-auto" >

        <TopBar/>
        {children}
        </div>
        <BottomBar/>
      </body>
    </html>
  );
}
